/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.activity.language.ui.quickfix;

import hu.bme.mit.gamma.action.language.ui.quickfix.ActionLanguageQuickfixProvider;

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
public class ActivityLanguageQuickfixProvider extends ActionLanguageQuickfixProvider {

//	@Fix(ActivityLanguageValidator.INVALID_NAME)
//	public void capitalizeName(final Issue issue, IssueResolutionAcceptor acceptor) {
//		acceptor.accept(issue, "Capitalize name", "Capitalize the name.", "upcase.png", new IModification() {
//			public void apply(IModificationContext context) throws BadLocationException {
//				IXtextDocument xtextDocument = context.getXtextDocument();
//				String firstLetter = xtextDocument.get(issue.getOffset(), 1);
//				xtextDocument.replace(issue.getOffset(), 1, firstLetter.toUpperCase());
//			}
//		});
//	}

}
