<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.mit.bme.hu/gamma/genmodel/Model" nsPrefix="hu.bme.mit.gamma.yakindu.genmodel">
  <eClassifiers xsi:type="ecore:EClass" name="GenModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statechartImports" upperBound="-1"
        eType="ecore:EClass ../../org.yakindu.sct.model.sgraph/model/emf/sgraph.ecore#//Statechart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packageImports" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceImports" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.trace.model/model/trace.ecore#//ExecutionTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genmodelImports" upperBound="-1"
        eType="#//GenModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioImports" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.scenario.model/model/scenario.ecore#//ScenarioPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetFolder" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeout" eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//TimeSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iterationCount" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceCompilation" eSuperTypes="#//YakinduCompilation"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatechartCompilation" eSuperTypes="#//YakinduCompilation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceMappings" upperBound="-1"
        eType="#//InterfaceMapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statechartName" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeGeneration" eSuperTypes="#//AbstractCodeGeneration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisModelTransformation" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="task" eType="#//AnalysisTask"
        defaultValueLiteral="TRANSFORMATION"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="languages" unique="false"
        lowerBound="1" upperBound="-1" eType="#//AnalysisLanguage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scheduler" unique="false"
        upperBound="-1" eType="#//Scheduler"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverages" upperBound="-1"
        eType="#//Coverage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optimize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optimizeEnvironmentalMessageQueues"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" eType="#//Constraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//ModelReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyPackage" eType="ecore:EClass ../../hu.bme.mit.gamma.property.model/model/property.ecore#//PropertyPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialState" eType="ecore:EClass ../../hu.bme.mit.gamma.property.model/model/property.ecore#//PropertyPackage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialStateSetting" eType="#//InitialStateSetting"
        defaultValueLiteral="EXECUTE_ENTRY_ACTIONS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnalysisTask">
    <eLiterals name="TRANSFORMATION"/>
    <eLiterals name="TRANSFORMATION_AND_VERIFICATION" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InitialStateSetting">
    <eLiterals name="EXECUTE_ENTRY_ACTIONS" literal="EXECUTE_ENTRY_ACTIONS"/>
    <eLiterals name="SKIP_ENTRY_ACTIONS" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceMapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="realizationMode" lowerBound="1"
        eType="ecore:EEnum ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//RealizationMode"
        defaultValueLiteral="PROVIDED"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yakinduInterface" lowerBound="1"
        eType="ecore:EClass ../../org.yakindu.sct.model.stext/model/SText.ecore#//InterfaceScope"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gammaInterface" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventMappings" upperBound="-1"
        eType="#//EventMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="yakinduEvent" lowerBound="1"
        eType="ecore:EClass ../../org.yakindu.base.types/model/types.ecore#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gammaEvent" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProgrammingLanguage">
    <eLiterals name="JAVA"/>
    <eLiterals name="C" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnalysisLanguage">
    <eLiterals name="UPPAAL"/>
    <eLiterals name="THETA" value="1"/>
    <eLiterals name="XSTS_UPPAAL" value="2" literal="XSTS_UPPAAL"/>
    <eLiterals name="PROMELA" value="3" literal="PROMELA"/>
    <eLiterals name="NUXMV" value="4" literal="NUXMV"/>
    <eLiterals name="OCRA" value="5" literal="OCRA"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YakinduCompilation" abstract="true"
      eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statechart" lowerBound="1"
        eType="ecore:EClass ../../org.yakindu.sct.model.sgraph/model/emf/sgraph.ecore#//Statechart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestGeneration" eSuperTypes="#//AbstractCodeGeneration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionTrace" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.trace.model/model/trace.ecore#//ExecutionTrace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Scheduler">
    <eLiterals name="RANDOM"/>
    <eLiterals name="FAIR" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionCoverage" eSuperTypes="#//Coverage"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateCoverage" eSuperTypes="#//Coverage"/>
  <eClassifiers xsi:type="ecore:EClass" name="Coverage" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="include" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//ComponentInstanceReferenceExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exclude" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//ComponentInstanceReferenceExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventPriorityTransformation" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statechart" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/statechart.ecore#//StatechartDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutEventCoverage" eSuperTypes="#//EventCoverage"/>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionCoverage" eSuperTypes="#//EventCoverage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="senderCoverageCriterion"
        eType="#//InteractionCoverageCriterion"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="receiverCoverageCriterion"
        eType="#//InteractionCoverageCriterion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateInclude" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//ComponentInstanceStateReferenceExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateExclude" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//ComponentInstanceStateReferenceExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitionInclude" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//ComponentInstanceTransitionReferenceExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitionExclude" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//ComponentInstanceTransitionReferenceExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InteractionCoverageCriterion">
    <eLiterals name="EVERY_INTERACTION"/>
    <eLiterals name="STATES_AND_EVENTS" value="1"/>
    <eLiterals name="EVENTS" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SchedulingConstraint" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceConstraint" upperBound="-1"
        eType="#//AsynchronousInstanceConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrchestratingConstraint" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="minimumPeriod" eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//TimeSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maximumPeriod" eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//TimeSpecification"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AsynchronousInstanceConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="orchestratingConstraint"
        lowerBound="1" eType="#//OrchestratingConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//ComponentInstanceReferenceExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCodeGeneration" abstract="true"
      eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="programmingLanguages" upperBound="-1"
        eType="#//ProgrammingLanguage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractComplementaryTestGeneration"
      abstract="true" eSuperTypes="#//AbstractCodeGeneration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testFolder" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdaptiveContractTestGeneration" eSuperTypes="#//AbstractComplementaryTestGeneration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelTransformation" lowerBound="1"
        eType="#//AnalysisModelTransformation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdaptiveBehaviorConformanceChecking"
      eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelTransformation" lowerBound="1"
        eType="#//AnalysisModelTransformation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmentModel" eType="#//ComponentReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhaseStatechartGeneration" eSuperTypes="#//Task ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ArgumentedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statechart" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/statechart.ecore#//StatechartDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Verification" eSuperTypes="#//AbstractComplementaryTestGeneration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="svgFileName" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="analysisLanguages" lowerBound="1"
        upperBound="-1" eType="#//AnalysisLanguage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="queryFiles" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verificationArguments"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyPackages" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.property.model/model/property.ecore#//PropertyPackage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optimizeModel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optimizeOutEvents" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optimize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backAnnotateToOriginal"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceGeneration" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullTraces" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variables" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noTransitionCoverage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableLists" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceReplayModelGeneration" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionTraceFolder" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionTrace" eType="ecore:EClass ../../hu.bme.mit.gamma.trace.model/model/trace.ecore#//ExecutionTrace"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="environmentModelFileName"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="environmentModel" lowerBound="1"
        eType="#//EnvironmentModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="considerOutEvents" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="analysisLanguages" upperBound="-1"
        eType="#//AnalysisLanguage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnvironmentModel">
    <eLiterals name="OFF" literal="OFF"/>
    <eLiterals name="SYNCHRONOUS" value="1" literal="SYNCHRONOUS"/>
    <eLiterals name="ASYNCHRONOUS" value="2" literal="ASYNCHRONOUS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelReference" abstract="true" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ArgumentedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentReference" eSuperTypes="#//ModelReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XstsReference" eSuperTypes="#//ModelReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="xSts" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.xsts.model/model/model.ecore#//XSTS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slicing" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyPackage" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.property.model/model/property.ecore#//PropertyPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionPairCoverage" eSuperTypes="#//Coverage"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventCoverage" abstract="true" eSuperTypes="#//Coverage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="portInclude" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//ComponentInstancePortReferenceExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portExclude" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//ComponentInstancePortReferenceExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataflowCoverage" eSuperTypes="#//Coverage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableInclude" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//ComponentInstanceVariableReferenceExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableExclude" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//ComponentInstanceVariableReferenceExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataflowCoverageCriterion"
        eType="#//DataflowCoverageCriterion" defaultValueLiteral="ALL_USE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataflowCoverageCriterion">
    <eLiterals name="ALL_DEF" literal="ALL_DEF"/>
    <eLiterals name="ALL_P_USE" value="1"/>
    <eLiterals name="ALL_C_USE" value="2"/>
    <eLiterals name="ALL_USE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionDataflowCoverage" eSuperTypes="#//EventCoverage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interactionDataflowCoverageCriterion"
        eType="#//DataflowCoverageCriterion" defaultValueLiteral="ALL_USE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatechartContractTestGeneration" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentReference" eType="#//ComponentReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" eType="#//OrchestratingConstraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatechartContractGeneration" eSuperTypes="#//Task ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ArgumentedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenario" eType="ecore:EClass ../../hu.bme.mit.gamma.scenario.model/model/scenario.ecore#//ScenarioDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StartAsColdViolation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UseIteratingVariable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AutomatonType" eType="#//ContractAutomatonType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TestType" eType="#//TestAutomatonType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RestartOnAccept" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContractAutomatonType">
    <eLiterals name="MONITOR"/>
    <eLiterals name="TEST" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TestAutomatonType">
    <eLiterals name="POSITIVE"/>
    <eLiterals name="NEGATIVE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SafetyAssessment" abstract="true" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="analysisModelTransformation"
        eType="#//AnalysisModelTransformation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faultExtensionInstructionsFile"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faultModesFile" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyPackages" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.property.model/model/property.ecore#//PropertyPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faultExtensionInstructions"
        eType="ecore:EClass ../../hu.bme.mit.gamma.fei.model/model/fei.ecore#//FaultExtensionInstructions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visualize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaultTreeGeneration" eSuperTypes="#//SafetyAssessment"/>
  <eClassifiers xsi:type="ecore:EClass" name="FmeaTableGeneration" eSuperTypes="#//SafetyAssessment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cardinality" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bmcBound" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelMutation" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//ModelReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patternClassNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MutationBasedTestGeneration" eSuperTypes="#//AbstractComplementaryTestGeneration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="analysisModelTransformation"
        lowerBound="1" eType="#//AnalysisModelTransformation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="traceFolders" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testClassNamePattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patternClassNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
