/*
 * generated by Xtext
 */
package hu.bme.mit.gamma.statechart.language.ui.wizard;

import org.eclipse.osgi.util.NLS;

public class Messages extends NLS {
	private static final String BUNDLE_NAME = "hu.bme.mit.gamma.statechart.language.ui.wizard.messages"; //$NON-NLS-1$
	
	public static String HelloWorldProject_Label;
	public static String HelloWorldProject_Description;
	public static String GenericStochasticGammaProject_Label;
	public static String GenericStochasticGammaProject_Description;
	public static String IoTStochasticGammaProject_Label;
	public static String IoTStochasticGammaProject_Description;
	public static String CrossroadGammaProject_Label;
	public static String CrossroadGammaProject_Description;
	
	static {
	// initialize resource bundle
	NLS.initializeMessages(BUNDLE_NAME, Messages.class);
	}
	
	private Messages() {
	}
}
