/*
 * generated by Xtext 2.15.0
 */
package hu.bme.mit.gamma.action.language.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import hu.bme.mit.gamma.action.language.ActionLanguageRuntimeModule;
import hu.bme.mit.gamma.action.language.ActionLanguageStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ActionLanguageIdeSetup extends ActionLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ActionLanguageRuntimeModule(), new ActionLanguageIdeModule()));
	}
	
}
