/*
 * generated by Xtext 2.15.0
 */
package hu.bme.mit.gamma.action.language.ide;


/**
 * Use this class to register ide components.
 */
public class ActionLanguageIdeModule extends AbstractActionLanguageIdeModule {
}
