/*
 * generated by Xtext 2.15.0
 */
package hu.bme.mit.gamma.action.language;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ActionLanguageRuntimeModule extends AbstractActionLanguageRuntimeModule {
}
