<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.mit.bme.hu/gamma/property/Model" nsPrefix="hu.bme.mit.gamma.property">
  <eClassifiers xsi:type="ecore:EClass" name="PropertyPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formulas" upperBound="-1"
        eType="#//CommentableStateFormula" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contracts" upperBound="-1"
        eType="#//Contract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommentableStateFormula" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//CommentableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="formula" lowerBound="1"
        eType="#//StateFormula" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathFormula" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateFormula" abstract="true" eSuperTypes="#//PathFormula"/>
  <eClassifiers xsi:type="ecore:EClass" name="TemporalPathFormula" abstract="true"
      eSuperTypes="#//PathFormula"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryOperandPathFormula" eSuperTypes="#//TemporalPathFormula">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
        eType="#//PathFormula" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//UnaryPathOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryOperandPathFormula" eSuperTypes="#//TemporalPathFormula">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" lowerBound="1"
        eType="#//PathFormula" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" lowerBound="1"
        eType="#//PathFormula" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//BinaryPathOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryPathOperator">
    <eLiterals name="UNTIL"/>
    <eLiterals name="RELEASE" value="1"/>
    <eLiterals name="WEAK_UNTIL" value="2" literal="WEAK_UNTIL"/>
    <eLiterals name="STRONG_RELEASE" value="5" literal="STRONG_RELEASE"/>
    <eLiterals name="BEFORE" value="3" literal="BEFORE"/>
    <eLiterals name="WEAK_BEFORE" value="4" literal="WEAK_BEFORE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnaryPathOperator">
    <eLiterals name="GLOBAL"/>
    <eLiterals name="FUTURE" value="1"/>
    <eLiterals name="NEXT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuantifiedFormula" eSuperTypes="#//StateFormula">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantifier" lowerBound="1"
        eType="#//PathQuantifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formula" lowerBound="1"
        eType="#//PathFormula" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PathQuantifier">
    <eLiterals name="FORALL"/>
    <eLiterals name="EXISTS" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicFormula" eSuperTypes="#//StateFormula">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryLogicalOperator">
    <eLiterals name="AND"/>
    <eLiterals name="XOR" value="1"/>
    <eLiterals name="OR" value="2"/>
    <eLiterals name="IMPLY" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnaryLogicalOperator">
    <eLiterals name="NOT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryOperandLogicalPathFormula" eSuperTypes="#//PathFormula">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//UnaryLogicalOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
        eType="#//PathFormula" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryOperandLogicalPathFormula" eSuperTypes="#//PathFormula">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//BinaryLogicalOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" lowerBound="1"
        eType="#//PathFormula" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" lowerBound="1"
        eType="#//PathFormula" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assume" lowerBound="1"
        eType="#//StateFormula" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guarantee" lowerBound="1"
        eType="#//StateFormula" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//ComponentInstanceReferenceExpression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
