/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.activity.language.ide;


/**
 * Use this class to register ide components.
 */
public class ActivityLanguageIdeModule extends AbstractActivityLanguageIdeModule {
}
