/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.activity.language.ide;

import org.eclipse.xtext.util.Modules2;

import com.google.inject.Guice;
import com.google.inject.Injector;

import hu.bme.mit.gamma.activity.language.ActivityLanguageRuntimeModule;
import hu.bme.mit.gamma.activity.language.ActivityLanguageStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ActivityLanguageIdeSetup extends ActivityLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ActivityLanguageRuntimeModule(), new ActivityLanguageIdeModule()));
	}
	
}
