/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.activity.language.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class ActivityLanguageOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
