<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="traceability" nsURI="http://www.mit.bme.hu/gamma/yakindu/transformation/Traceability"
    nsPrefix="hu.bme.mit.gamma.yakindu.transformation">
  <eClassifiers xsi:type="ecore:EClass" name="Y2GTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="yakinduStatechart" eType="ecore:EClass ../../org.yakindu.sct.model.sgraph/model/emf/sgraph.ecore#//Statechart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gammaStatechart" eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/statechart.ecore#//StatechartDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traces" upperBound="-1"
        eType="#//AbstractTrace" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTrace" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionTrace" eSuperTypes="#//AbstractTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trace" eSuperTypes="#//AbstractTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
</ecore:EPackage>
