A[] not deadlock
E<> P_interruptedOfInterruptedOfcrossroad_prior.Black && isStable
E<> P_interruptedOfInterruptedOfcrossroad_prior.BlinkingYellow && isStable
E<> P_interruptedOfInterruptedOfcrossroad_secondary.Black && isStable
E<> P_interruptedOfInterruptedOfcrossroad_secondary.BlinkingYellow && isStable
E<> P_main_regionOfStatechartOfcrossroad_controller.Interrupted && isStable
E<> P_main_regionOfStatechartOfcrossroad_controller.Operating && isStable
E<> P_main_regionOfStatechartOfcrossroad_prior.Interrupted && isStable
E<> P_main_regionOfStatechartOfcrossroad_prior.Normal && isStable
E<> P_main_regionOfStatechartOfcrossroad_secondary.Interrupted && isStable
E<> P_main_regionOfStatechartOfcrossroad_secondary.Normal && isStable
E<> P_main_regionOfStatechartOfmonitor.Error && isStable
E<> P_main_regionOfStatechartOfmonitor.Green && isStable
E<> P_main_regionOfStatechartOfmonitor.Other && isStable
E<> P_main_regionOfStatechartOfmonitor.Red && isStable
E<> P_normalOfNormalOfcrossroad_prior.Green && isStable
E<> P_normalOfNormalOfcrossroad_prior.Red && isStable
E<> P_normalOfNormalOfcrossroad_prior.Yellow && isStable
E<> P_normalOfNormalOfcrossroad_secondary.Green && isStable
E<> P_normalOfNormalOfcrossroad_secondary.Red && isStable
E<> P_normalOfNormalOfcrossroad_secondary.Yellow && isStable
E<> P_operatingOfOperatingOfcrossroad_controller.Init && isStable
E<> P_operatingOfOperatingOfcrossroad_controller.Priority && isStable
E<> P_operatingOfOperatingOfcrossroad_controller.PriorityPrepares && isStable
E<> P_operatingOfOperatingOfcrossroad_controller.Secondary && isStable
E<> P_operatingOfOperatingOfcrossroad_controller.SecondaryPrepares && isStable
