<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ActivityComposition" nsURI="http://www.mit.bme.hu/gamma/statechart/Model/ActivityComposition"
    nsPrefix="hu.bme.mit.gamma.statechart.activitycomposition">
  <eClassifiers xsi:type="ecore:EClass" name="ActivityDefinition" eSuperTypes="composite.ecore#//StatefulComponent ../../hu.bme.mit.gamma.activity.model/model/activity.ecore#//CompositeNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="SynchronousActivityDefinition" eSuperTypes="composite.ecore#//SynchronousComponent #//ActivityDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="TriggerNode" eSuperTypes="../../hu.bme.mit.gamma.activity.model/model/activity.ecore#//ControlNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" lowerBound="1"
        eType="ecore:EClass interface.ecore#//Trigger" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityControllerPort" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="#//ActivityDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceActivityControllerPortReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" lowerBound="1"
        eType="ecore:EClass composite.ecore#//ComponentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="#//ActivityControllerPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityControllerPortConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="provided" lowerBound="1"
        eType="ecore:EClass composite.ecore#//ComponentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="required" lowerBound="1"
        eType="#//InstanceActivityControllerPortReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunActivityAction" eSuperTypes="../../hu.bme.mit.gamma.action.model/model/action.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
        eType="#//ActivityControllerPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityDerivedAnnotation" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityControllerPortAnnotation" eSuperTypes="#//ActivityDerivedAnnotation interface.ecore#//PortAnnotation"/>
</ecore:EPackage>
