<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="composite" nsURI="http://www.mit.bme.hu/gamma/statechart/Model/Composite"
    nsPrefix="hu.bme.mit.gamma.statechart.composite">
  <eClassifiers xsi:type="ecore:EClass" name="PrioritizedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeComponent" abstract="true"
      eSuperTypes="interface.ecore#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="portBindings" upperBound="-1"
        eType="#//PortBinding" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channels" upperBound="-1"
        eType="#//Channel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchedulableCompositeComponent" abstract="true"
      eSuperTypes="#//CompositeComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialExecutionList" upperBound="-1"
        eType="#//ComponentInstanceReferenceExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionList" upperBound="-1"
        eType="#//ComponentInstanceReferenceExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstance" abstract="true" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//NamedElement ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ArgumentedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PortBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositeSystemPort" lowerBound="1"
        eType="ecore:EClass interface.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instancePortReference"
        lowerBound="1" eType="#//InstancePortReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Channel" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedPort" lowerBound="1"
        eType="#//InstancePortReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstancePortReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" lowerBound="1"
        eType="#//ComponentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass interface.ecore#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BroadcastChannel" eSuperTypes="#//Channel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredPorts" lowerBound="1"
        upperBound="-1" eType="#//InstancePortReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleChannel" eSuperTypes="#//Channel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredPort" lowerBound="1"
        eType="#//InstancePortReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlFunction" eType="#//ControlFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" lowerBound="1"
        eType="ecore:EClass interface.ecore#//SimpleTrigger" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ControlFunction">
    <eLiterals name="RUN_ONCE"/>
    <eLiterals name="RUN_TO_COMPLETION" value="1"/>
    <eLiterals name="RESET" value="2"/>
    <eLiterals name="RESET_MESSAGE_QUEUE" value="3" literal="RESET_MESSAGE_QUEUE"/>
    <eLiterals name="RESET_MESSAGE_QUEUES" value="4"/>
    <eLiterals name="RESET_OTHER_MESSAGE_QUEUES" value="5" literal="RESET_OTHER_MESSAGE_QUEUES"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageQueue" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//NamedElement #//PrioritizedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="capacity" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventPassings" lowerBound="1"
        upperBound="-1" eType="#//EventPassing" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventDiscardStrategy" eType="#//DiscardStrategy"
        defaultValueLiteral="INCOMING"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventPassing">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass interface.ecore#//EventReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass interface.ecore#//EventReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SynchronousComponent" abstract="true"
      eSuperTypes="interface.ecore#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="AsynchronousComponent" abstract="true"
      eSuperTypes="interface.ecore#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="SynchronousComponentInstance" eSuperTypes="#//ComponentInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//SynchronousComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AsynchronousComponentInstance" eSuperTypes="#//ComponentInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//AsynchronousComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractSynchronousCompositeComponent"
      abstract="true" eSuperTypes="#//CompositeComponent #//SynchronousComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//SynchronousComponentInstance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractAsynchronousCompositeComponent"
      eSuperTypes="#//CompositeComponent #//AsynchronousComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//AsynchronousComponentInstance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AsynchronousCompositeComponent" eSuperTypes="#//AbstractAsynchronousCompositeComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScheduledAsynchronousCompositeComponent"
      eSuperTypes="#//AbstractAsynchronousCompositeComponent #//SchedulableCompositeComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="AsynchronousAdapter" eSuperTypes="#//AsynchronousComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlSpecifications"
        lowerBound="1" upperBound="-1" eType="#//ControlSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messageQueues" upperBound="-1"
        eType="#//MessageQueue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clocks" upperBound="-1"
        eType="ecore:EClass interface.ecore#//Clock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wrappedComponent" lowerBound="1"
        eType="#//SynchronousComponentInstance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CascadeCompositeComponent" eSuperTypes="#//AbstractSynchronousCompositeComponent #//SchedulableCompositeComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="SynchronousCompositeComponent" eSuperTypes="#//AbstractSynchronousCompositeComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstanceReferenceExpression"
      eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ReferenceExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstance" lowerBound="1"
        eType="#//ComponentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" eType="#//ComponentInstanceReferenceExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DiscardStrategy">
    <eLiterals name="INCOMING"/>
    <eLiterals name="OLDEST" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstanceElementReferenceExpression"
      abstract="true" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="#//ComponentInstanceReferenceExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstanceStateReferenceExpression"
      eSuperTypes="#//ComponentInstanceElementReferenceExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" lowerBound="1"
        eType="ecore:EClass statechart.ecore#//Region"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" eType="ecore:EClass statechart.ecore#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstanceVariableReferenceExpression"
      eSuperTypes="#//ComponentInstanceElementReferenceExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableDeclaration" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//VariableDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstancePortReferenceExpression"
      eSuperTypes="#//ComponentInstanceElementReferenceExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass interface.ecore#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstanceEventReferenceExpression"
      eSuperTypes="#//ComponentInstanceElementReferenceExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass interface.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="ecore:EClass interface.ecore#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstanceEventParameterReferenceExpression"
      eSuperTypes="#//ComponentInstanceElementReferenceExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass interface.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="ecore:EClass interface.ecore#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterDeclaration" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ParameterDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstanceTransitionReferenceExpression"
      eSuperTypes="#//ComponentInstanceElementReferenceExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitionId" lowerBound="1"
        eType="ecore:EClass statechart.ecore#//TransitionIdAnnotation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstanceReflectiveElementReferenceExpression"
      eSuperTypes="#//ComponentInstanceElementReferenceExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
