<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="statechart" nsURI="http://www.mit.bme.hu/gamma/statechart/Model/Statechart"
    nsPrefix="hu.bme.mit.gamma.statechart">
  <eClassifiers xsi:type="ecore:EClass" name="StatechartDefinition" abstract="true"
      eSuperTypes="interface.ecore#//Component #//CompositeElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableDeclarations" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//VariableDeclaration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeoutDeclarations" upperBound="-1"
        eType="#//TimeoutDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schedulingOrder" lowerBound="1"
        eType="#//SchedulingOrder" defaultValueLiteral="TOP_DOWN"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orthogonalRegionSchedulingOrder"
        lowerBound="1" eType="#//OrthogonalRegionSchedulingOrder" defaultValueLiteral="SEQUENTIAL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitionPriority" lowerBound="1"
        eType="#//TransitionPriority" defaultValueLiteral="OFF"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guardEvaluation" lowerBound="1"
        eType="#//GuardEvaluation" defaultValueLiteral="ON_THE_FLY"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invariants" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SynchronousStatechartDefinition" eSuperTypes="#//StatechartDefinition composite.ecore#//SynchronousComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="AsynchronousStatechartDefinition" eSuperTypes="#//StatechartDefinition composite.ecore#//AsynchronousComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="capacity" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SchedulingOrder">
    <eLiterals name="TOP_DOWN"/>
    <eLiterals name="BOTTOM_UP" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OrthogonalRegionSchedulingOrder">
    <eLiterals name="SEQUENTIAL"/>
    <eLiterals name="UNORDERED" value="1" literal="UNORDERED"/>
    <eLiterals name="PARALLEL" value="2" literal="PARALLEL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TransitionPriority">
    <eLiterals name="OFF"/>
    <eLiterals name="ORDER_BASED" value="1"/>
    <eLiterals name="VALUE_BASED" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GuardEvaluation">
    <eLiterals name="ON_THE_FLY"/>
    <eLiterals name="BEGINNING_OF_STEP" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeoutDeclaration" eSuperTypes="interface.ecore#//EventSource"/>
  <eClassifiers xsi:type="ecore:EClass" name="Region" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateNodes" upperBound="-1"
        eType="#//StateNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateNode" abstract="true" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//StateNode #//CompositeElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invariants" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryActions" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.action.model/model/action.ecore#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exitActions" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.action.model/model/action.ecore#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//StateAnnotation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateReferenceExpression" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//NullaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" lowerBound="1"
        eType="#//Region"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" eType="#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PseudoState" abstract="true" eSuperTypes="#//StateNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChoiceState" eSuperTypes="#//PseudoState"/>
  <eClassifiers xsi:type="ecore:EClass" name="MergeState" eSuperTypes="#//PseudoState"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForkState" eSuperTypes="#//PseudoState"/>
  <eClassifiers xsi:type="ecore:EClass" name="JoinState" eSuperTypes="#//PseudoState"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitialState" eSuperTypes="#//EntryState"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="composite.ecore#//PrioritizedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceState" eType="#//StateNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetState" eType="#//StateNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" eType="ecore:EClass interface.ecore#//Trigger"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="effects" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.action.model/model/action.ecore#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//TransitionAnnotation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RaiseEventAction" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ArgumentedElement ../../hu.bme.mit.gamma.action.model/model/action.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="ecore:EClass interface.ecore#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass interface.ecore#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeoutAction" abstract="true" eSuperTypes="../../hu.bme.mit.gamma.action.model/model/action.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeoutDeclaration" lowerBound="1"
        eType="#//TimeoutDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetTimeoutAction" eSuperTypes="#//TimeoutAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="time" lowerBound="1" eType="ecore:EClass interface.ecore#//TimeSpecification"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeactivateTimeoutAction" eSuperTypes="#//TimeoutAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntryState" abstract="true" eSuperTypes="#//PseudoState"/>
  <eClassifiers xsi:type="ecore:EClass" name="ShallowHistoryState" eSuperTypes="#//EntryState"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeepHistoryState" eSuperTypes="#//EntryState"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnyPortEventReference" eSuperTypes="interface.ecore#//EventReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass interface.ecore#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortEventReference" eSuperTypes="interface.ecore#//EventReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="ecore:EClass interface.ecore#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass interface.ecore#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClockTickReference" eSuperTypes="interface.ecore#//EventReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clock" lowerBound="1" eType="ecore:EClass interface.ecore#//Clock"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeoutEventReference" eSuperTypes="interface.ecore#//EventReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeout" lowerBound="1"
        eType="#//TimeoutDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryTrigger" eSuperTypes="#//ComplexTrigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" lowerBound="1"
        eType="ecore:EClass interface.ecore#//Trigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" lowerBound="1"
        eType="ecore:EClass interface.ecore#//Trigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//BinaryType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexTrigger" abstract="true" eSuperTypes="interface.ecore#//Trigger"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryType">
    <eLiterals name="AND" literal="AND"/>
    <eLiterals name="OR" value="1"/>
    <eLiterals name="EQUAL" value="2" literal="EQUAL"/>
    <eLiterals name="XOR" value="4" literal="XOR"/>
    <eLiterals name="IMPLY" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryTrigger" eSuperTypes="#//ComplexTrigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
        eType="ecore:EClass interface.ecore#//Trigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//UnaryType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnaryType">
    <eLiterals name="NOT" literal="NOT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="regions" upperBound="-1"
        eType="#//Region" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpaqueTrigger" eSuperTypes="interface.ecore#//SimpleTrigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trigger" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OnCycleTrigger" eSuperTypes="interface.ecore#//SimpleTrigger"/>
  <eClassifiers xsi:type="ecore:EClass" name="MutantAnnotation" eSuperTypes="interface.ecore#//ComponentAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatechartAnnotation" abstract="true"
      eSuperTypes="interface.ecore#//ComponentAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="RunUponExternalEventAnnotation" eSuperTypes="#//StatechartAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="RunUponExternalEventOrInternalTimeoutAnnotation"
      eSuperTypes="#//StatechartAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateAnnotation" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionAnnotation" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionIdAnnotation" eSuperTypes="#//TransitionAnnotation ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeoutReferenceExpression" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ReferenceExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeout" lowerBound="1"
        eType="#//TimeoutDeclaration"/>
  </eClassifiers>
</ecore:EPackage>
