/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.activity.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ActivityLanguageUiModule extends AbstractActivityLanguageUiModule {

	public ActivityLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
