<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.mit.bme.hu/gamma/trace/Model" nsPrefix="hu.bme.mit.gamma.trace.model">
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionTrace" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//NamedElement ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ArgumentedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//ExecutionTraceAnnotation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableDeclarations" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//VariableDeclaration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
        eType="#//Step" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="import" eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cycle" eType="#//Cycle"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Step">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Act" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asserts" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Act" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RaiseEventAct" eSuperTypes="#//Act ../../hu.bme.mit.gamma.statechart.model/model/statechart.ecore#//RaiseEventAction ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeElapse" eSuperTypes="#//Act">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elapsedTime" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schedule" abstract="true" eSuperTypes="#//Act"/>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceSchedule" eSuperTypes="#//Schedule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceReference" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/composite.ecore#//ComponentInstanceReferenceExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentSchedule" eSuperTypes="#//Schedule"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssignmentAct" eSuperTypes="#//Act">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ReferenceExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cycle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
        eType="#//Step" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reset" eSuperTypes="#//Act"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionTraceAnnotation" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionTraceAllowedWaitingAnnotation"
      eSuperTypes="#//ExecutionTraceAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowerLimit" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperLimit" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NegativeTestAnnotation" eSuperTypes="#//ExecutionTraceAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionTraceCommentAnnotation" eSuperTypes="#//ExecutionTraceAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
