<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.mit.bme.hu/gamma/xSTS/Model" nsPrefix="hu.bme.mit.gamma.xsts">
  <eClassifiers xsi:type="ecore:EClass" name="XSTS" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//XstsAnnotation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeDeclarations" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//TypeDeclaration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publicTypeDeclarations"
        upperBound="-1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//TypeDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableDeclarations" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//VariableDeclaration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableGroups" upperBound="-1"
        eType="#//VariableGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableInitializingTransition"
        lowerBound="1" eType="#//XTransition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurationInitializingTransition"
        lowerBound="1" eType="#//XTransition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryEventTransition" lowerBound="1"
        eType="#//XTransition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//XTransition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inEventTransition" lowerBound="1"
        eType="#//XTransition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outEventTransition" lowerBound="1"
        eType="#//XTransition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XTransition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reads" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//VariableDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writes" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//VariableDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimedVariable" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="primedVariable" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//VariableDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentGroup" eType="#//VariableGroup"
        eOpposite="#//VariableGroup/containedGroups"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedGroups" upperBound="-1"
        eType="#//VariableGroup" eOpposite="#//VariableGroup/parentGroup"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" lowerBound="1"
        eType="#//GroupAnnotation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//VariableDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupAnnotation" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RegionGroup" eSuperTypes="#//GroupAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventGroup" abstract="true" eSuperTypes="#//GroupAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentGroup" eSuperTypes="#//GroupAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="PlainVariableGroup" eSuperTypes="#//GroupAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//ActionAnnotation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicAction" abstract="true" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="NonDeterministicAction" eSuperTypes="#//MultiaryAction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A single child action is executed. Suitable for the description of choices witch AssumeActions."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequentialAction" eSuperTypes="#//MultiaryAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnorderedAction" eSuperTypes="#//MultiaryAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelAction" eSuperTypes="#//MultiaryAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssumeAction" eSuperTypes="#//AtomicAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assumption" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmptyAction" eSuperTypes="#//AtomicAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssignmentAction" eSuperTypes="#//AbstractAssignmentAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiaryAction" abstract="true" eSuperTypes="#//CompositeAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" lowerBound="1"
        upperBound="-1" eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeoutGroup" eSuperTypes="#//GroupAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentParameterGroup" eSuperTypes="#//GroupAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="InEventGroup" eSuperTypes="#//EventGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutEventGroup" eSuperTypes="#//EventGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventParameterGroup" abstract="true"
      eSuperTypes="#//GroupAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutEventParameterGroup" eSuperTypes="#//EventParameterGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="InEventParameterGroup" eSuperTypes="#//EventParameterGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrthogonalAction" eSuperTypes="#//MultiaryAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemInEventGroup" eSuperTypes="#//EventGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemOutEventGroup" eSuperTypes="#//EventGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemInEventParameterGroup" eSuperTypes="#//EventParameterGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemOutEventParameterGroup" eSuperTypes="#//EventParameterGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="MessageQueueGroup" abstract="true" eSuperTypes="#//GroupAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="MasterMessageQueueGroup" eSuperTypes="#//MessageQueueGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="SlaveMessageQueueGroup" eSuperTypes="#//MessageQueueGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemMasterMessageQueueGroup" eSuperTypes="#//MessageQueueGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemSlaveMessageQueueGroup" eSuperTypes="#//MessageQueueGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="MessageQueueSizeGroup" eSuperTypes="#//MessageQueueGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclarationAction" eSuperTypes="#//AtomicAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableDeclaration" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//VariableDeclaration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopAction" eSuperTypes="#//CompositeAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iterationParameterDeclaration"
        lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ParameterDeclaration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//IntegerRangeLiteralExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfAction" eSuperTypes="#//CompositeAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" lowerBound="1" eType="#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" lowerBound="1" eType="#//Action"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeAction" abstract="true" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssertAction" eSuperTypes="#//AtomicAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assertion" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HavocAction" eSuperTypes="#//AbstractAssignmentAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractAssignmentAction" abstract="true"
      eSuperTypes="#//AtomicAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ReferenceExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XstsAnnotation" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActionAnnotation" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InvariantAnnotation" abstract="true"
      eSuperTypes="#//ActionAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentalInvariantAnnotation" eSuperTypes="#//InvariantAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="InternalInvariantAnnotation" eSuperTypes="#//InvariantAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="OnDemandControlVariableDeclarationAnnotation"
      eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//VariableDeclarationAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="StrictControlVariableDeclarationAnnotation"
      eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//VariableDeclarationAnnotation"/>
</ecore:EPackage>
