/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.gamma.tutorial.extra.monitor;

import hu.bme.mit.gamma.tutorial.extra.IStatemachine;
import java.util.List;

public interface IMonitorStatemachine extends IStatemachine {
	public interface SCILightInputs {
	
		public void raiseDisplayRed();
		
		public void raiseDisplayGreen();
		
		public void raiseDisplayYellow();
		
		public void raiseDisplayNone();
		
	}
	
	public SCILightInputs getSCILightInputs();
	
	public interface SCIMonitor {
	
		public boolean isRaisedError();
		
	public List<SCIMonitorListener> getListeners();
	}
	
	public interface SCIMonitorListener {
	
		public void onErrorRaised();
		}
	
	public SCIMonitor getSCIMonitor();
	
}
