<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.mit.bme.hu/gamma/activity/Model" nsPrefix="hu.bme.mit.gamma.activity">
  <eClassifiers xsi:type="ecore:EClass" name="DataConduitNode" abstract="true" eSuperTypes="#//DataConduit #//PseudoActivityNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode" abstract="true" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControlFlow" eSuperTypes="#//Flow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceNode" lowerBound="1"
        eType="#//ActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetNode" lowerBound="1"
        eType="#//ActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFlow" eSuperTypes="#//Flow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataSource" lowerBound="1"
        eType="#//DataSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTarget" lowerBound="1"
        eType="#//DataTarget"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Flow" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSource" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataTarget" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActionNode" eSuperTypes="#//ActivityNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityDeclarationReference"
        eType="#//ActivityDeclarationReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataConduit" abstract="true" eSuperTypes="#//DataSource #//DataTarget"/>
  <eClassifiers xsi:type="ecore:EClass" name="JoinNode" eSuperTypes="#//DataConduitNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForkNode" eSuperTypes="#//DataConduitNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionNode" eSuperTypes="#//DataConduitNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="MergeNode" eSuperTypes="#//DataConduitNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="PseudoActivityNode" abstract="true"
      eSuperTypes="#//ActivityNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitialNode" eSuperTypes="#//PseudoActivityNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="FinalNode" eSuperTypes="#//PseudoActivityNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityDefinition" eSuperTypes="#//Definition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="flows" upperBound="-1"
        eType="#//Flow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityNodes" upperBound="-1"
        eType="#//ActivityNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableDeclarations" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//VariableDeclaration"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PinReference" abstract="true" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ReferenceExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputPin" eSuperTypes="#//Pin"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActionDefinition" eSuperTypes="#//Definition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.action.model/model/action.ecore#//Action"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Definition" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedActivityDeclaration" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//NamedElement #//ActivityDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="InlineActivityDeclaration" eSuperTypes="#//ActivityDeclaration #//ActivityDeclarationReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityDeclaration" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
        eType="#//Definition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pins" upperBound="-1" eType="#//Pin"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPin" eSuperTypes="#//Pin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pin" abstract="true" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPinReference" abstract="true" eSuperTypes="#//PinReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPin" lowerBound="1"
        eType="#//InputPin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPinReference" abstract="true"
      eSuperTypes="#//PinReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputPin" lowerBound="1"
        eType="#//OutputPin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InsideInputPinReference" eSuperTypes="#//InputPinReference #//DataSource #//InsidePinReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutsideInputPinReference" eSuperTypes="#//InputPinReference #//DataTarget #//OutsidePinReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="InsideOutputPinReference" eSuperTypes="#//OutputPinReference #//DataTarget #//InsidePinReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutsideOutputPinReference" eSuperTypes="#//OutputPinReference #//DataSource #//OutsidePinReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityDeclarationReference" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedActivityDeclarationReference" eSuperTypes="#//ActivityDeclarationReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="namedActivityDeclaration"
        lowerBound="1" eType="#//NamedActivityDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityPackage" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="namedActivityDeclarations"
        upperBound="-1" eType="#//NamedActivityDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InsidePinReference" abstract="true"
      eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutsidePinReference" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionNode" lowerBound="1"
        eType="#//ActionNode"/>
  </eClassifiers>
</ecore:EPackage>
