/*
 * generated by Xtext 2.12.0
 */
package hu.bme.mit.gamma.scenario.language

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ScenarioLanguageStandaloneSetup extends ScenarioLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new ScenarioLanguageStandaloneSetup().createInjectorAndDoEMFRegistration
	}
}
