/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.activity.language;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ActivityLanguageStandaloneSetup extends ActivityLanguageStandaloneSetupGenerated {

	public static void doSetup() {
		new ActivityLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
