/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.activity.language;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ActivityLanguageRuntimeModule extends AbstractActivityLanguageRuntimeModule {
}
