/*
 * generated by Xtext 2.15.0
 */
package hu.bme.mit.gamma.action.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ActionLanguageUiModule extends AbstractActionLanguageUiModule {

	public ActionLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
