/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.activity.language.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

import hu.bme.mit.gamma.action.language.formatting.ActionLanguageFormatterUtil;
import hu.bme.mit.gamma.activity.language.services.ActivityLanguageGrammarAccess;

/**
 * This class contains custom formatting declarations.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#formatting
 * on how and when to use it.
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormatter} as an example
 */
public class ActivityLanguageFormatter extends AbstractDeclarativeFormatter {

	private final ActionLanguageFormatterUtil actionLanguageFormatterUtil = new ActionLanguageFormatterUtil();
	
	@Override
	protected void configureFormatting(FormattingConfig c) {
		ActivityLanguageGrammarAccess f = (ActivityLanguageGrammarAccess) getGrammarAccess();
		actionLanguageFormatterUtil.format(c, f);
		actionLanguageFormatterUtil.formatExpressions(c, f.getActionLanguageGrammarAccess());
	}
	
}
