/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.activity.language.validation;

import org.eclipse.xtext.validation.Check;

import hu.bme.mit.gamma.activity.util.ActivityModelValidator;
import hu.bme.mit.gamma.expression.model.NamedElement;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class ActivityLanguageValidator extends AbstractActivityLanguageValidator {
	
	protected ActivityModelValidator activityModelValidator = ActivityModelValidator.INSTANCE;
	
	public ActivityLanguageValidator() {
		super.expressionModelValidator = activityModelValidator;
		super.actionModelValidator = activityModelValidator;
	}
	
	@Check
	public void checkNameUniqueness(NamedElement element) {
		handleValidationResultMessage(activityModelValidator.checkNameUniqueness(element));
	}
	
}
