/*
 * generated by Xtext 2.12.0
 */
package hu.bme.mit.gamma.scenario.language.ide


/**
 * Use this class to register ide components.
 */
class ScenarioLanguageIdeModule extends AbstractScenarioLanguageIdeModule {
}
