/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.activity.language.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;

import hu.bme.mit.gamma.action.model.Action;
import hu.bme.mit.gamma.activity.derivedfeatures.ActivityModelDerivedFeatures;
import hu.bme.mit.gamma.activity.model.ActivityDeclaration;
import hu.bme.mit.gamma.activity.model.ActivityDefinition;
import hu.bme.mit.gamma.activity.model.ActivityModelPackage;
import hu.bme.mit.gamma.activity.model.Flow;
import hu.bme.mit.gamma.activity.model.InsidePinReference;
import hu.bme.mit.gamma.activity.model.OutsidePinReference;
import hu.bme.mit.gamma.activity.model.PinReference;
import hu.bme.mit.gamma.expression.model.ExpressionModelPackage;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class ActivityLanguageScopeProvider extends AbstractActivityLanguageScopeProvider {
	
	@Override
	public IScope getScope(final EObject context, final EReference reference) {

		try {			
			if (context instanceof Action &&
					reference == ExpressionModelPackage.Literals.DIRECT_REFERENCE_EXPRESSION__DECLARATION) {
				IScope parentScope = getParentScope(context, reference);
				EObject container = context.eContainer();
				if (container instanceof Flow) {
					ActivityDefinition definition = ActivityModelDerivedFeatures.getContainingActivityDefinition(context);
					return Scopes.scopeFor(definition.getVariableDeclarations(), parentScope);
				}
				return parentScope;
			}
			
			if (context instanceof PinReference) {
				
				if (context instanceof InsidePinReference) {
					ActivityDeclaration declaration = ActivityModelDerivedFeatures.getContainingActivityDeclaration(context);
					
					return Scopes.scopeFor(declaration.getPins());
				}
				else { // instanceof OutsidePinReference
					if (reference == ActivityModelPackage.Literals.OUTSIDE_PIN_REFERENCE__ACTION_NODE) {
						ActivityDefinition definition = ActivityModelDerivedFeatures.getContainingActivityDefinition(context);
						
						return Scopes.scopeFor(definition.getActivityNodes());
					}
					if (reference == ActivityModelPackage.Literals.OUTPUT_PIN_REFERENCE__OUTPUT_PIN) {
						ActivityDeclaration declaration = ActivityModelDerivedFeatures.getReferencedActivityDeclaration((OutsidePinReference)context);
						
						return Scopes.scopeFor(declaration.getPins());
					}
					if (reference == ActivityModelPackage.Literals.INPUT_PIN_REFERENCE__INPUT_PIN) {
						ActivityDeclaration declaration = ActivityModelDerivedFeatures.getReferencedActivityDeclaration((OutsidePinReference)context);
						
						return Scopes.scopeFor(declaration.getPins());
					}
					
				} 
				
			}
		} catch (Exception e) {
			e.printStackTrace();
		} 
		
		return super.getScope(context, reference);
	}
	
}
