/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.gamma.activity.language.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class ActivityLanguageScopeProvider extends AbstractActivityLanguageScopeProvider {

}
