<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.mit.bme.hu/gamma/scenario/Model" nsPrefix="hu.bme.mit.gamma.scenario">
  <eClassifiers xsi:type="ecore:EClass" name="ScenarioPackage" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ExpressionPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" lowerBound="1"
        upperBound="-1" eType="#//ScenarioDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScenarioDeclaration" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//NamedElement ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ParametricElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" upperBound="-1"
        eType="#//Annotation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialBlock" eType="#//InitialBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableDeclarations" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//VariableDeclaration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragment" lowerBound="1"
        eType="#//Fragment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Occurrence" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interactions" lowerBound="1"
        upperBound="-1" eType="#//Occurrence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CombinedFragment" abstract="true" eSuperTypes="#//Occurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" lowerBound="1"
        upperBound="-1" eType="#//Fragment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlternativeCombinedFragment" eSuperTypes="#//CombinedFragment"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnorderedCombinedFragment" eSuperTypes="#//CombinedFragment"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelCombinedFragment" eSuperTypes="#//CombinedFragment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interaction" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ArgumentedElement #//DeterministicOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//InteractionDirection"
        defaultValueLiteral="RECEIVE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modality" lowerBound="1"
        eType="#//ModalityType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModalityType">
    <eLiterals name="COLD"/>
    <eLiterals name="HOT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InteractionDirection">
    <eLiterals name="RECEIVE" value="1"/>
    <eLiterals name="SEND"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeterministicOccurrenceSet" eSuperTypes="#//DeterministicOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deterministicOccurrences"
        upperBound="-1" eType="#//DeterministicOccurrence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopCombinedFragment" eSuperTypes="#//CombinedFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="minimum" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maximum" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionalCombinedFragment" eSuperTypes="#//CombinedFragment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Delay" eSuperTypes="#//DeterministicOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="minimum" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maximum" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NegatedDeterministicOccurrence" eSuperTypes="#//DeterministicOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deterministicOccurrence"
        lowerBound="1" eType="#//DeterministicOccurrence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="WaitAnnotation" eSuperTypes="#//Annotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="minimum" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maximum" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeterministicOccurrence" abstract="true"
      eSuperTypes="#//Occurrence"/>
  <eClassifiers xsi:type="ecore:EClass" name="StrictAnnotation" eSuperTypes="#//Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="PermissiveAnnotation" eSuperTypes="#//Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="NegatedWaitAnnotation" eSuperTypes="#//Annotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="minimum" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maximum" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NegStrictAnnotation" eSuperTypes="#//Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="NegPermissiveAnnotation" eSuperTypes="#//Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitialBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interactions" lowerBound="1"
        upperBound="-1" eType="#//DeterministicOccurrence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScenarioDefinitionReference" eSuperTypes="#//Occurrence ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ArgumentedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioDefinition" lowerBound="1"
        eType="#//ScenarioDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScenarioCheckExpression" eSuperTypes="#//DeterministicOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScenarioAssignmentStatement" eSuperTypes="#//DeterministicOccurrence ../../hu.bme.mit.gamma.action.model/model/action.ecore#//AssignmentStatement"/>
</ecore:EPackage>
