<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.mit.bme.hu/gamma/scenario/Model" nsPrefix="hu.bme.mit.gamma.scenario">
  <eClassifiers xsi:type="ecore:EClass" name="ScenarioDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" lowerBound="1"
        upperBound="-1" eType="#//ScenarioDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScenarioDefinition" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="chart" lowerBound="1" eType="#//Chart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" upperBound="-1"
        eType="#//Annotation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialblock" eType="#//InitialBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragment" lowerBound="1"
        eType="#//InteractionFragment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interaction" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interactions" lowerBound="1"
        upperBound="-1" eType="#//Interaction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CombinedFragment" abstract="true" eSuperTypes="#//Interaction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" lowerBound="1"
        upperBound="-1" eType="#//InteractionFragment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlternativeCombinedFragment" eSuperTypes="#//CombinedFragment"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnorderedCombinedFragment" eSuperTypes="#//CombinedFragment"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelCombinedFragment" eSuperTypes="#//CombinedFragment"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModalInteraction" abstract="true" eSuperTypes="#//InteractionDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modality" lowerBound="1"
        eType="#//ModalityType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reset" eSuperTypes="#//ModalInteraction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Signal" eSuperTypes="../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//ArgumentedElement #//ModalInteraction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.gamma.statechart.model/model/interface.ecore#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//InteractionDirection"
        defaultValueLiteral="RECEIVE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModalityType">
    <eLiterals name="COLD"/>
    <eLiterals name="HOT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InteractionDirection">
    <eLiterals name="RECEIVE" value="1"/>
    <eLiterals name="SEND"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModalInteractionSet" eSuperTypes="#//InteractionDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modalInteractions" upperBound="-1"
        eType="#//InteractionDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopCombinedFragment" eSuperTypes="#//CombinedFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="minimum" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maximum" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionalCombinedFragment" eSuperTypes="#//CombinedFragment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Delay" eSuperTypes="#//ModalInteraction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="minimum" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maximum" eType="ecore:EClass ../../hu.bme.mit.gamma.expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NegatedModalInteraction" eSuperTypes="#//InteractionDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modalinteraction" lowerBound="1"
        eType="#//InteractionDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="WaitAnnotation" eSuperTypes="#//Annotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionDefinition" abstract="true"
      eSuperTypes="#//Interaction"/>
  <eClassifiers xsi:type="ecore:EClass" name="StrictAnnotation" eSuperTypes="#//Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="PermissiveAnnotation" eSuperTypes="#//Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="NegatedWaitAnnotation" eSuperTypes="#//Annotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NegStrictAnnotation" eSuperTypes="#//Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="NegPermissiveAnnotation" eSuperTypes="#//Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitialBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modalInteractions" lowerBound="1"
        upperBound="-1" eType="#//ModalInteraction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartAsColdViolationAnnotation" eSuperTypes="#//Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="DedicatedColdViolationAnnotation" eSuperTypes="#//Annotation"/>
</ecore:EPackage>
