/*
 * generated by Xtext 2.15.0
 */
package hu.bme.mit.gamma.action.language.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
public class ActionLanguageProposalProvider extends AbstractActionLanguageProposalProvider {
}
